version: '3'
services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: epushserver
      MYSQL_USER: epush1
      MYSQL_PASSWORD: epush1
  #  ports:
  #    - "3306:3306"
    volumes:
     - ./db:/docker-entrypoint-initdb.d
     - ./mysql/my.cnf:/etc/my.cnf

  web:
    image: tomcat:7.0.105-jdk8-openjdk
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    environment:
      JDBC_URL: jdbc:mysql://db:3306/epushserver?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: epush1
      JDBC_PASS: epush1
    ports:
     - "0.0.0.0:8888:8080"
    volumes:
     - ./ePushserver/iclock:/usr/local/tomcat/webapps/iclock
    links:
      - db